import { Injectable } from '@angular/core';
import { Router } from '@angular/router';
import { find } from 'rxjs';
import { mueble } from '../models/mueble';

@Injectable({
  providedIn: 'root',
})
export class MuebleServiceLocalService {
  public muebles: mueble[];

  constructor(private route: Router) {
    this.muebles = [
      /*Menu de Sillones de 0 a 16*/
      new mueble(
        1,
        'Sillón Modena',
        'Colección Modena',
        'Sillón',
        'Es uno de los muebles básicos de la Colección Modena. Está pensado para ofrecer múltiples combinaciones. Junto con la dos versiones de Puff Modena, nos permite armar un rinconero transformándose en un juego de living completo. Opcionales: 1,2, 3 cuerpos, c/s apoyabrazos y Chaise Loungue. Mirá la Colección Modena completa',
        'Con apoyabrazo: An 2.155 mm. /Al 0.735 mm. /Prof 0.738 mm.   Sin apoyabrazo: An 2.070 mm. /Al 0.735 mm./Prof 0.738 mm.     Chaise Modena: An 2.120 mm. /Al 0.735 mm./Prof 0.738 mm. ',
        'https://i.ibb.co/N2KHN1y/Croquis-Sillon-modena.png',
        'https://i.ibb.co/tQ3j8wc/2-1-1.jpg',
        'https://i.ibb.co/hLKK5Sj/2-1-2.jpg',
        'https://i.ibb.co/Y2W7dZQ/2-1-3.jpg',
        'https://i.ibb.co/WWQ4R78/2-1-4.jpg',
        ''
      ),
      new mueble(
        2,
        'Sillón Modena / 1 Cuerpo',
        'Colección Modena',
        'Sillón',
        'Es uno de los muebles básicos de la Colección Modena. Está pensado para ofrecer múltiples combinaciones.un rinconero adaptable -junto con las dos versiones de Puff Modena,- y un juego de living completo-acoplado con el Sillón Modena de 2 cuerpos-. Opcionales:1, 2, 3 cuerpos, c/s apoyabrazos y tipo Chaise Loungue.',
        'Con apoyabrazo: 1 Cuerpo : An 0.785 mm./ Al 0.735 mm. / Prof 0.738 mm. 2 cuerpos: An 1.470 mm. /Al 0.735 mm. /Prof 0.738 mm. 3 cuerpos: An 2.155 mm. /Al 0.735 mm. /Prof 0.738 mm.',
        'https://i.ibb.co/1zgPdt0/sillon-modena-croquis.jpg',
        'https://i.ibb.co/MVm8P0n/2-2-1.jpg',
        'https://i.ibb.co/nwhJy8F/2-2-2.jpg',
        'https://i.ibb.co/G3yPLhh/2-2-3.jpg',
        'https://i.ibb.co/XXPS0bb/2-2-4.jpg',
        ''
      ),
      new mueble(
        3,
        'Sillón Modena / Comedor',
        'Colección Modena',
        'Sillón',
        'Sillón para comedor con apoyabrazos. Realizado en aluminio anodizado con perfilería 50 x 50 mm.',
        'Con apoyabrazo: 1 Cuerpo : An 0.600 mm./ Al 0.850 mm. / Prof 0.620 mm. ',
        '',
        'https://i.ibb.co/TLcysx2/2-16-1.jpg',
        'https://i.ibb.co/s6L5fbW/2-16-2.jpg',
        'https://i.ibb.co/zNxnSp1/2-16-3.jpg',
        'https://i.ibb.co/FYwhyrM/2-16-4.jpg',
        ''
      ),
      new mueble(
        4,
        'Sillón Formentera / Recto.',
        'Colección Formentera',
        'Sillón',
        'Sillón Formentera / Recto. Se caracteriza las líneas rectas en sus ángulos a 90º. Elegancia atemporal y ensamble perfecto de sus atractivas formas tanto rectas como curvilíneas. s. Diseño opcional: Curvo. Opcionales: 1, 2, 3 cuerpos y tipo “Chaise Longue Formentera”*, -el apoyabrazos podés elegirlo del lado derecho o izquierdo-.',
        '1 Cuerpo: An: 740 mm. / Al: 740mm. / Prof: 740 mm 2 Cuerpos: An: 1425 mm. / Al: 740mm. / Prof: 740 mm. 3 Cuerpos: An: 2100 mm. / Al: 740mm. / Prof: 740 mm.',
        'https://i.ibb.co/Mcx28Tc/sillon-formentera-croquis.jpg',
        'https://i.ibb.co/80Sbx17/1-1-1.jpg',
        'https://i.ibb.co/1JNwddd/1-1-2.jpg',
        'https://i.ibb.co/MSb48St/1-1-3.jpg',
        'https://i.ibb.co/PTkC9LS/1-1-4.jpg',
        'https://i.ibb.co/RP5ch1j/1-1-5.jpg'
      ),
      new mueble(
        5,
        'Sillón Formentera / Curvo.',
        'Colección Formentera',
        'Sillón',
        'e caracteriza las líneas curvas en sus ángulos. Elegancia atemporal y ensamble perfecto de sus atractivas formas tanto rectas como curvilíneas. Diseño Opcional: Recto. Opcionales: 1, 2 y 3 cuerpos y tipo “Chaise Longue F” -el apoyabrazos podés elegirlo del lado derecho o izquierdo-.',
        '1 Cuerpo: An: 740 mm. / Al: 740mm. / Prof: 740 mm. 2 Cuerpos: An: 1425 mm. / Al: 740mm. / Prof: 740 mm. 3 Cuerpos: An: 2100 mm. / Al: 740mm. / Prof: 740 mm.',
        'https://i.ibb.co/Mcx28Tc/sillon-formentera-croquis.jpg',
        'https://i.ibb.co/1bk09dD/1-2-1.jpg',
        'https://i.ibb.co/ns6DRzT/1-2-2.jpg',
        'https://i.ibb.co/f4HpQZQ/1-2-3.jpg',
        '',
        ''
      ),
      new mueble(
        6,
        'Sillón Formentera / Max.',
        'Colección Formentera',
        'Sillón',
        'Robusto Sillón diseñado con un perfil de aluminio simple recto, con un ensamble perfecto entre sus atractivas terminaciones tanto rectas como curvilíneas.',
        '1 Cuerpo: An 1330 mm. /Al 550 mm. /Prof 1040 mm || 2 Cuerpos: An 2030 mm. /Al 550 mm. /Prof 1040 mm',
        'https://i.ibb.co/TqDVs5L/sillon-formentera-max.jpg',
        'https://i.ibb.co/nDSVYq2/1-3-2.jpg',
        'https://i.ibb.co/H4P96JJ/1-3-1.jpg',
        'https://i.ibb.co/wYWJ60Q/1-3-3.jpg',
        '',
        ''
      ),
      new mueble(
        7,
        'Sillón Tirreno Plus.',
        'Colección Tirreno',
        'Sillón',
        'La Colección T Plus refuerza su diseño, enfatizando sus líneas con perfilería 75 x 50mm. Esta Colección se destaca por tener sólo un parante posterior en su diseño. Es ideal para crear un Living muy personal. Los almohadones están confeccionados en tela náutica un textil resistente a los efectos de los rayos UV y del agua.',
        '1C // 950 mm. x 850 mm. x 780 mm. 2C // 1.750 mm. x 850 mm. x 780 mm.',
        '',
        'https://i.ibb.co/JRp1f3g/3-6-1.jpg',
        'https://i.ibb.co/9NH9BLB/3-6-2.jpg',
        'https://i.ibb.co/j3pdJSS/3-6-3.jpg',
        'https://i.ibb.co/5WxJkTp/3-6-4.jpg',
        ''
      ),
      new mueble(
        8,
        'Sillón Tirreno Plus / 2 Cuerpos.',
        'Colección Tirreno',
        'Sillón',
        'La Colección T Plus refuerza su diseño, enfatizando sus líneas con perfilería 75 x 50mm. Esta Colección se destaca por tener sólo un parante posterior en su diseño. Es ideal para crear un Living muy personal. Los almohadones están confeccionados en tela náutica un textil resistente a los efectos de los rayos UV y del agua.',
        '1C // 950 mm. x 850 mm. x 780 mm. || 2C // 1.750 mm. x 850 mm. x 780 mm.',
        '',
        'https://i.ibb.co/zb3J3ZL/3-7-1.jpg',
        'https://i.ibb.co/RTwdxnd/3-7-2.jpg',
        'https://i.ibb.co/Rc83xQ2/3-7-3.jpg',
        'https://i.ibb.co/4PmFyCt/3-7-4.jpg',
        'https://i.ibb.co/fHSZyJ2/3-7-5.jpg'
      ),
      new mueble(
        9,
        'Sillón Tirreno / 1 Cuerpo.',
        'Colección Tirreno',
        'Sillón',
        'Sillón Tirreno -1 cuerpo-. Modelo único en su tipo. Se destaca por tener sólo un parante posterior en su diseño. Es ideal para crear un Living muy personal. Los almohadones están confeccionados en tela náutica un textil resistente a los efectos de los rayos UV y del agua. Se puede complementar el juego con el Sillón Tirreno de 2 cuerpos. Opcionales: 1, 2, cuerpos, c/s apoyabrazos y tipo Chaise Loungue',
        '1 Cuerpo: An 0.785 mm. /Al 0.730 mm. /Prof 0.735 mm. 2 Cuerpos: Al 1.470 mm. /Al 0.730 mm. /Prof 0.735 mm.',
        'https://i.ibb.co/vmsCDcM/croquis-tirreno.jpg',
        'https://i.ibb.co/XCycSSD/3-1-1.jpg',
        'https://i.ibb.co/5BKfcqc/3-1-2.jpg',
        'https://i.ibb.co/CKSpPqh/3-1-3.jpg',
        'https://i.ibb.co/wzjJGLV/3-1-4.jpg',
        ''
      ),
      new mueble(
        10,
        'Sillón Tirreno / 2 Cuerpos.',
        'Colección Tirreno',
        'Sillón',
        'Sillón Tirreno -2 cuerpos-. Modelo único en su tipo. Se destaca por tener sólo un parante posterior en su diseño. Es ideal para crear un Living muy personal. Los almohadones están confeccionados en tela náutica un textil resistente a los efectos de los rayos UV y del agua. Se puede complementar el juego con el Sillón Tirreno de 2 cuerpos. Opcionales: 1, 2, cuerpos, c/s apoyabrazos y tipo Chaise Lo',
        '1 Cuerpo: An 0.785 mm. /Al 0.730 mm. /Prof 0.735 mm. 2 Cuerpos: Al 1.470 mm. /Al 0.730 mm. /Prof 0.735 mm.',
        'https://i.ibb.co/vmsCDcM/croquis-tirreno.jpg',
        'https://i.ibb.co/cxtmbvP/3-2-1.jpg',
        'https://i.ibb.co/mqhcLwC/3-2-2.jpg',
        'https://i.ibb.co/VNqwLXK/3-2-3.jpg',
        '',
        ''
      ),
      new mueble(
        11,
        'Sillón Dot / 1 Cuerpo.',
        'Colección Dot',
        'Sillón',
        'Con perfiles innovadores, tanto rectos como curvos, la Coleccion Dot se caracteriza por sus laterales y respaldos cubiertos de aluminio punzonado. Esto le da un diferencial especial frente al resto de las colecciones.',
        '1 Cuerpos: An 730 mm. /Al 680 mm. /Prof 730 mm. 2 Cuerpos: An 1370 mm. /Al 680mm. /Prof 730 mm.',
        'https://i.ibb.co/BKXrt3S/sillones-dot-croquis.jpg',
        'https://i.ibb.co/f1qVj4H/5-2-1.jpg',
        'https://i.ibb.co/0nf8KMx/5-2-2.jpg',
        'https://i.ibb.co/vhp9vnW/5-2-3.jpg',
        'https://i.ibb.co/y6B9yWF/5-2-4.jpg',
        'https://i.ibb.co/FKzZPfT/5-2-5.jpg'
      ),
      new mueble(
        12,
        'Sillón Dot /  2 Cuerpos.',
        'Colección Dot',
        'Sillón',
        'Con perfiles innovadores, tanto rectos como curvos, la Coleccion Dot se caracteriza por sus laterales y respaldos cubiertos de aluminio punzonado. Esto le da un diferencial especial frente al resto de las colecciones.',
        '1 Cuerpos: An 730 mm. /Al 680 mm. /Prof 730 mm. 2 Cuerpos: An 1370 mm. /Al 680mm. /Prof 730 mm.',
        'https://i.ibb.co/BKXrt3S/sillones-dot-croquis.jpg',
        'https://i.ibb.co/ZLYVFyy/5-1-1.jpg',
        'https://i.ibb.co/986hLfG/5-1-2.jpg',
        'https://i.ibb.co/2SC0DMc/5-1-3.jpg',
        'https://i.ibb.co/3CwRZ1W/5-1-4.jpg',
        ''
      ),
      new mueble(
        13,
        'Sillón Belt /  1 Cuerpo.',
        'Colección Belt',
        'Sillón',
        'Empleando una nueva técnica, logramos líneas curvas y elegantes que dan como resultado un diseño único! Esta nueva línea está integrada por varios productos, es simple y divertida a la vez. Con sus diferentes piezas, esta colección nos propone jugar para armar diferentes diseños de livings. Con estructura de aluminio anodizado o pintado y tapicería en tela Sunbrella, Belt es para exterior!',
        'BELT 1 Cuerpo: An 800 mm./Al 620 mm./Prof 950 mm. BELT 2 Cuerpos: An 1600 mm./Al 620 mm./Prof 950 mm. BELT 3 Cuerpos: An 2200 mm./Al 620 mm./Prof 950 mm.',
        'https://i.ibb.co/8zn96mp/sillon-belt-1-cuerpo-croquis.jpg',
        'https://i.ibb.co/TB23jrh/7-1-1.jpg',
        'https://i.ibb.co/9wfpKxn/7-1-2.jpg',
        'https://i.ibb.co/f8YkSGg/7-1-3.jpg',
        'https://i.ibb.co/D47GsMg/7-1-4.jpg',
        ''
      ),
      new mueble(
        14,
        'Sillón Belt /  2 Cuerpos.',
        'Colección Belt',
        'Sillón',
        'Empleando una nueva técnica, logramos líneas curvas y elegantes que dan como resultado un diseño único! Esta nueva línea está integrada por varios productos, es simple y divertida a la vez. Con sus diferentes piezas, esta colección nos propone jugar para armar diferentes diseños de livings. Con estructura de aluminio anodizado o pintado y tapicería en tela Sunbrella, Belt es para exterior!',
        'BELT 1 Cuerpo: An 800 mm./Al 620 mm./Prof 950 mm. BELT 2 Cuerpos: An 1600 mm./Al 620 mm./Prof 950 mm. BELT 3 Cuerpos: An 2200 mm./Al 620 mm./Prof 950 mm.',
        'https://i.ibb.co/8gX1Ns3/sillon-belt-2-cuerpos-croquis.jpg',
        'https://i.ibb.co/ZhsFvQ3/7-2-1.jpg',
        'https://i.ibb.co/0jVgLSB/7-2-2.jpg',
        'https://i.ibb.co/0jVgLSB/7-2-2.jpg',
        '',
        ''
      ),
      new mueble(
        15,
        'Sillón Belt /  3 Cuerpos.',
        'Colección Belt',
        'Sillón',
        'Empleando una nueva técnica, logramos líneas curvas y elegantes que dan como resultado un diseño único! Esta nueva línea está integrada por varios productos, es simple y divertida a la vez. Con sus diferentes piezas, esta colección nos propone jugar para armar diferentes diseños de livings. Con estructura de aluminio anodizado o pintado y tapicería en tela Sunbrella, Belt es para exterior!',
        'BELT 1 Cuerpo: An 800 mm./Al 620 mm./Prof 950 mm. BELT 2 Cuerpos: An 1600 mm./Al 620 mm./Prof 950 mm. BELT 3 Cuerpos: An 2200 mm./Al 620 mm./Prof 950 mm.',
        'https://i.ibb.co/7kG51CX/sillon-belt-3-cuerpos-croquis.jpg',
        'https://i.ibb.co/xY3y4WJ/7-3-1.jpg',
        'https://i.ibb.co/vzBx2qq/7-3-2.jpg',
        'https://i.ibb.co/prk3wnD/7-3-3.jpg',
        'https://i.ibb.co/CmcjQGn/7-3-4.jpg',
        ''
      ),
      new mueble(
        16,
        'Sillón Relax',
        'Colección Especial',
        'Sillón',
        'Sillón Relax. Cómodo y esbelto mueble, jerarquiza todo espacio donde se encuentre, tanto interior como exterior. diseñada con un perfil de aluminio simple recto, con un ensamble perfecto entre sus atractivas terminaciones tanto rectas como curvilíneas. Se puede complementar con el Apoyapié o Puff Relax.',
        '1 Cuerpos: An 750 mm. / Al 1100 mm. / Prof 1100 mm. 2 Cuerpos: An 1500 mm. /Al 1100 mm. / Prof 1100 mm.',
        'https://i.ibb.co/GvJBJ3d/sillon-relax-croquis.jpg',
        'https://i.ibb.co/3h3FJzw/9-2-1.jpg',
        'https://i.ibb.co/M5xJykT/9-2-2.jpg',
        'https://i.ibb.co/XjP6vCx/9-2-3.jpg',
        'https://i.ibb.co/TMK5z2P/9-2-4.jpg',
        ''
      ),
      /*mesas*/
      new mueble(
        17,
        'Mesa Modena / Comedor',
        'Colección Modena',
        'Mesas',
        'Mesa de comedor Modena. Fabricada en aluminio anodizado. Se destaca por la unión de los perfiles a 45º. Puede usarse tanto en ambientes exteriores e interiores. Opcionales de tapa: varillas de aluminio, perfiles de aluminio en “U”, tapa de laminado decorativo fenólico sólido fabricado a alta presión.',
        '900: An 0.900 mm. /Alt 0.760 mm. /Prof 0.900 mm.  || 1200: An 1.200 mm. /Alt 0.760 mm. /Prof 0.900 mm. || 1800: An 1.800 mm. /Alt 0.760 mm. /Prof 0.900 mm.  || 2200: An 2.200 mm. /Alt 0.760 mm. /Prof 1.000 mm. || 2500: An 2.500 mm. /Alt 0.760 mm. /Prof 1.100 mm.',
        '',
        'https://i.ibb.co/synbCVt/2-7-1.jpg',
        'https://i.ibb.co/G5Y0gbS/2-7-2.jpg',
        'https://i.ibb.co/YXRq5X8/2-7-3.jpg',
        'https://i.ibb.co/mB42pr6/2-7-4.jpg',
        ''
      ),
      new mueble(
        18,
        'Mesa Formentera / Comedor',
        'Colección Formentera',
        'Mesas',
        'Diseñada con un perfil de aluminio simple con un ensamble perfecto entre sus atractivas terminaciones rectas. Opciones de Tapa: varillas de aluminio o tapa de laminado decorativo fenólico sólido fabricado a alta presión.',
        '70 x 70: An: 700 mm. / Alt. 760 mm. / Prof. 700 mm. || 90 x 86: An: 900 mm. /Alt. 760 mm. / Prof. 865 mm. || 120 x 86: An: 1200 mm. /Alt. 760 mm. / Prof. 865 mm. || 120 x 119: An: 1200 mm. /Alt. 760 mm. / Prof. 1190 mm. || 150 x 95: An: 1500 mm. /Alt. 760 mm. / Prof. 947 mm.',
        'https://i.ibb.co/bJDvCGp/mesa-formentera-comedor-croquis.jpg',
        'https://i.ibb.co/jytH0D3/1-7-1.jpg',
        'https://i.ibb.co/255Kg4J/1-7-2.jpg',
        'https://i.ibb.co/sVdJxLG/1-7-3.jpg',
        'https://i.ibb.co/cryntpb/1-7-4.jpg',
        ''
      ),
      new mueble(
        19,
        'Mesa Modena / Reposera',
        'Colección Modena',
        'Mesas',
        'Mesa lateral para acompañar nuestra reposeras. Realizada en aluminio anodizado o pintado, con perfiles de 50 x 50mm. Parte superior con varillas de aluminio. Opcional: tapa de Corian.',
        'an: 400 mm / alt: 370 mm /prof: 400 mm',
        '',
        'https://i.ibb.co/0m0zwF3/2-5-1.jpg',
        'https://i.ibb.co/bRt2szM/2-5-2.jpg',
        'https://i.ibb.co/g3Z1kN5/2-5-3.jpg',
        'https://i.ibb.co/W29pT7r/2-5-4.jpg',
        'https://i.ibb.co/SQVcCFt/2-5-5.jpg'
      ),
      new mueble(
        20,
        'Mesa Formentera / Reposera',
        'Colección Formentera',
        'Mesas',
        'Mesa lateral para acompañar nuestra reposeras. Realizada en aluminio anodizado o pintado, con perfiles de 75 x 50mm. Parte superior con varillas de aluminio. Diseñada con un perfil de aluminio simple recto, con un ensamble perfecto entre sus atractivas terminaciones.',
        'An: 400 mm / Alt: 370 mm / Prof: 400 mm',
        '',
        'https://i.ibb.co/yfZWBSz/1-6-1.jpg',
        'https://i.ibb.co/S51JFf2/1-6-2.jpg',
        'https://i.ibb.co/dkQd9yg/1-6-3.jpg',
        '',
        ''
      ),
      new mueble(
        21,
        'Mesa Modena / Ratona',
        'Colección Modena',
        'Mesas',
        'Living Modular. Mesa ratona de la Colección Modena. Está pensada para combinar con cualquiera de los muebles de Soma, permitiéndonos completar el juego de living modular. Opciones de tapa: con tablillas de aluminio o vidrio.',
        'An: 1000 mm / Alt: 370 mm / Prof: 600 mm',
        '',
        'https://i.ibb.co/4jwZKZk/2-6-1.jpg',
        'https://i.ibb.co/vHg450S/2-6-2.jpg',
        'https://i.ibb.co/xMkTCB6/2-6-3.jpg',
        '',
        ''
      ),
      new mueble(
        22,
        'Mesa Modena / Auxiliar',
        'Colección Modena',
        'Mesas',
        'Mesa auxiliar. Modelo de mesa de asistencia universal, combina perfectamente con todas las colecciones de Rivera Designs. Su diseño permite integrarla a diferentes situaciones y mobiliarios. Fabricada en aluminio anodizado. Este modelo tiene 2 variantes: mesa simple o mesa de doble función (permite ser usada tanto vertical como horizontalmente). Opciones de Tapa: varillas de aluminio o tapa de lam',
        'Mesa auxiliar / Reposera: An 0.450 mm. /Alt 0.450 mm. /Prof 0.500 mm. || Mesa auxiliar / Simple: An 0.450 mm. /Alt 0.680 mm. /Prof 0.500 mm. || Mesa auxiliar / Doble: An 0.450 mm. /Alt 0.680 mm. /Prof 0.500 mm.',
        '',
        'https://i.ibb.co/YfLzY9J/2-8-5.jpg',
        'https://i.ibb.co/8NPX0jf/2-8-6.jpg',
        'https://i.ibb.co/khmHMKb/2-8-7.jpg',
        'https://i.ibb.co/3sYVpS9/2-8-3.jpg',
        'https://i.ibb.co/9Vq21fM/2-8-8.jpg'
      ),
      new mueble(
        23,
        'Mesa Tirreno Plus / Ratona',
        'Colección Tirreno',
        'Mesas',
        'La Colección T Plus refuerza su diseño, enfatizando sus líneas con perfilería 75 x 50mm. Opciones de Tapa: varillas de aluminio, perfiles de aluminio o tapa de laminado decorativo fenólico sólido fabricado a alta presión.',
        'Plus 1: 800 mm. x 370 mm. x 500 mm. ||Plus 2: 1000 mm. x 370 mm. x 600 mm. ||Plus 3: 1000 mm. x 370 mm. x 1000 mm.',
        '',
        'https://i.ibb.co/rmPMZ4x/3-8-1.jpg',
        'https://i.ibb.co/1Jdf2kC/3-8-2.jpg',
        'https://i.ibb.co/RQLK050/3-8-3.jpg',
        'https://i.ibb.co/8X9x03s/3-8-4.jpg',
        ''
      ),
      new mueble(
        24,
        'Mesa Alumad / Comedor',
        'Colección Alumad',
        'Mesas',
        'Alumad presenta la combinación perfecta entre aluminio y madera en su versión ecológica y sintética. En todas las piezas de esta Coleccion, la estructura es de aluminio anodizado o pintado y la parte superior es de tablas de deck sintético, evitando todo tipo de deterioro al estar expuesto al sol y el agua. Disponemos de tres tonos de deck: blanco, marrón y gris.',
        '1 Cuerpo: An 1500 mm. /Al 760 mm. /Prof 800 mm. || 2 Cuerpos: An 1800 mm. /Al 760 mm. /Prof 800 mm. || 3 Cuerpos: An 2300 mm. /Al 760 mm. /Prof 800 mm.',
        'https://i.ibb.co/RbVxBhB/mesa-alumad-croquis.jpg',
        'https://i.ibb.co/fQbd7t0/6-1-1.jpg',
        'https://i.ibb.co/rsjh685/6-1-2.jpg',
        'https://i.ibb.co/ngxNTsG/6-1-3.jpg',
        'https://i.ibb.co/DkG792k/6-1-4.jpg',
        ''
      ),
      new mueble(
        25,
        'Mesa Alumad / Reposera',
        'Colección Alumad',
        'Mesas',
        'Alumad presenta la combinación perfecta entre aluminio y madera en su versión ecológica y sintética. En todas las piezas de esta Coleccion, la estructura es de aluminio anodizado o pintado y la parte superior es de tablas de deck sintético, evitando todo tipo de deterioro al estar expuesto al sol y el agua. Disponemos de tres tonos de deck: blanco, marrón y gris.',
        'ancho: 450 mm / alto: 380 mm / prof: 500 mm',
        'https://i.ibb.co/5FmfgRd/mesa-reposera-alumad-croquis.jpg',
        'https://i.ibb.co/j5Pc6GN/6-2-1.jpg',
        'https://i.ibb.co/M2zCcm7/6-2-2.jpg',
        'https://i.ibb.co/p3z7xwv/6-2-3.jpg',
        'https://i.ibb.co/DkG792k/6-1-4.jpg',
        ''
      ),
      new mueble(
        26,
        'Mesa Deck / Comedor',
        'Colección Deck',
        'Mesas',
        'Aluminio + Deck. Mesa exterior fabricada en aluminio anodizado, combinado con tapa en Deck de PVC color marrón es muy resistente a la intemperie. Podés armar el juego de comedor completo con la Silla Deck.',
        'ancho: 1300 mm / alto: 760 mm / prof: 890 mm',
        '',
        'https://i.ibb.co/2hCPYB9/8-3-1.jpg',
        'https://i.ibb.co/SPb2cM1/8-3-2.jpg',
        'https://i.ibb.co/SPb2cM1/8-3-2.jpg',
        '',
        ''
      ),
      new mueble(
        27,
        'Mesa Belt / Ratona',
        'Colección Belt',
        'Mesas',
        'Empleando una nueva técnica, logramos líneas curvas y elegantes que dan como resultado un diseño único! Esta nueva línea está integrada por varios productos, es simple y divertida a la vez. Con sus diferentes piezas, esta colección nos propone jugar para armar diferentes diseños de livings. Con estructura de aluminio anodizado o pintado y tapicería en tela Sunbrella, Belt es para exterior!.',
        'ancho: 640 mm / alto: 380 mm / prof: 1000 mm',
        '',
        'https://i.ibb.co/7yvBdZC/7-5-1.jpg',
        'https://i.ibb.co/9YVtLjQ/7-5-2.jpg',
        'https://i.ibb.co/V2Q9b1H/7-5-3.jpg',
        'https://i.ibb.co/Lr8FjjM/7-5-4.jpg',
        ''
      ),
      new mueble(
        28,
        'Mesa Glass Party',
        'Colección Especial',
        'Mesas',
        'Mesa ratona compuesta por una tapa de vidrio seguro -laminado y templado- con el interior relleno de vidrio templado partido.',
        'ancho: 950 mm / alto: 430 mm / prof: 600 mm',
        '',
        'https://i.ibb.co/1n0dmMz/9-3-1.jpg',
        'https://i.ibb.co/nk9MPqw/9-3-2.jpg',
        'https://i.ibb.co/nk9MPqw/9-3-2.jpg',
        '',
        ''
      ),
      new mueble(
        29,
        'Mesa Elevable',
        'Colección Especial',
        'Mesas',
        'Apertura en tres tiempos. Estapráctica mesa ratona posee amortiguación, freno y traba de seguridad. La tapa está revestida en melamina símil madera. Su funcionalidad es ideal para acercarla los objetos al usuario sin moverse de su lugar.',
        'ancho: 850 mm / alto: 490 mm / prof: 850 mm',
        '',
        'https://i.ibb.co/N1LytJG/9-4-1.jpg',
        'https://i.ibb.co/h27XJmT/9-4-2.jpg',
        'https://i.ibb.co/h27XJmT/9-4-2.jpg',
        '',
        ''
      ),
      /*Puff*/
      new mueble(
        30,
        'Puff Formentera / Curvo',
        'Colección Formentera',
        'Puff',
        'Puff Formentera / Curvo. Se caracteriza por las líneas curvas en sus ángulos. Elegancia atemporal y ensamble perfecto de sus atractivas formas tanto rectas como curvilíneas. Opcionales: 1, 2 y 3 cuerpos.',
        '1 Cuerpo: An 740 mm. / Al 380 mm. / Prof 740 mm. || 2 Cuerpos: An 1425 mm. / Al 380 mm. / Prof 740 mm. || 3 Cuerpos: An 2110 mm. / Al 380 mm. / Prof 740 mm',
        'https://i.ibb.co/BrJPBY4/puff-formentera.jpg',
        'https://i.ibb.co/9h6Z6kx/1-4-1.jpg',
        'https://i.ibb.co/Tqwh9vz/1-4-2.jpg',
        'https://i.ibb.co/xhFgNm1/1-4-3.jpg',
        '',
        ''
      ),
      new mueble(
        31,
        'Puff Formentera / Relax',
        'Colección Formentera',
        'Puff',
        'Puff Relax -o apoyapié-. Es el complemento ideal para hacer juego con el sillón Relax. Forma parte de la Nueva Colección Formentera, diseñada con un perfil de aluminio simple recto, con un ensamble perfecto entre sus atractivas terminaciones tanto rectas como curvilíneas.',
        'ancho: 700 mm / alto: 250 mm / prof: 700 mm',
        'https://i.ibb.co/BrJPBY4/puff-formentera.jpg',
        'https://i.ibb.co/KwsvMLp/1-5-1.jpg',
        'https://i.ibb.co/HVmBfxj/1-5-3.jpg',
        'https://i.ibb.co/HVmBfxj/1-5-3.jpg',
        '',
        ''
      ),
      new mueble(
        32,
        'Puff Modena',
        'Colección Modena',
        'Puff',
        'El Puff Modena sin apoyabrazos, es uno de los muebles básicos de la Coleccion Modena. Está pensado para ofrecer múltiples combinaciones posibles. Las dos versiones de Puff M, nos permiten jugar con un rinconero adaptable y acoplado con el Sillón Modena de 1 y/o 2 cuerpos, o como Chaise Loungue, transformándose en un juego de living completo.',
        '"1 Cuerpo: An 0.780 mm. / Al 0.470 mm. / Prof 0.780 mm. || 2 Cuerpos: An 1.370 mm. / Al 0.470 mm. /Prof 0.780 mm.  ||  3 Cuerpos: An 2.050 mm. / Al 0.470 mm. / Prof 0.780 mm.',
        '',
        'https://i.ibb.co/w4H0ndZ/2-4-3.jpg',
        'https://i.ibb.co/tYkqnFz/2-4-4.jpg',
        'https://i.ibb.co/dsv3DPd/2-4-2.jpg',
        '',
        ''
      ),
      new mueble(
        33,
        'Puff Modena / Sunken',
        'Colección Modena',
        'Puff',
        'El Puff Modena Sunken, es uno de los muebles básicos de la Colección Modena. Está pensado para ofrecer múltiples combinaciones posibles. La diferencia con el Puff Modena, es que en esta versión, el almohadón va hundido dentro de la estructura. Amos modelos nos permiten jugar con un rinconero adaptable y acoplado con el Sillón de 1 y/o 2 cuerpos, se transforma en un juego de living completo. ',
        'ancho: 785 mm / alto: 490 mm / prof: 685 mm',
        '',
        'https://i.ibb.co/F4pS939/2-3-1.jpg',
        'https://i.ibb.co/F4pS939/2-3-1.jpg',
        'https://i.ibb.co/F4pS939/2-3-1.jpg',
        '',
        ''
      ),
      new mueble(
        34,
        'Puff Belt',
        'Colección Belt',
        'Puff',
        'Empleando una nueva técnica, logramos líneas curvas y elegantes que dan como resultado un diseño único! Esta nueva línea está integrada por varios productos, es simple y divertida a la vez. Con sus diferentes piezas, esta colección nos propone jugar para armar diferentes diseños de livings.Con estructura de aluminio anodizado o pintado y tapicería en tela Sunbrella, Belt es para exterior!',
        'ancho: 800 mm / alto: 400 mm / prof: 950 mm',
        '',
        'https://i.ibb.co/8zCxyyP/7-6-1.jpg',
        'https://i.ibb.co/z7XK7np/7-6-2.jpg',
        'https://i.ibb.co/z7XK7np/7-6-2.jpg',
        '',
        ''
      ),
      /*Reposeras*/
      new mueble(
        35,
        'Reposera Formentera / Phifertex®',
        'Colección Formentera',
        'Reposeras',
        'Diseñada con un perfil de aluminio simple recto, con un ensamble perfecto entre sus atractivas terminaciones tanto rectas como curviColeccions. Las cabecera es regulable según la necesidad de confort. Diseño opcional: Curvo -perfiles con ángulos curvos. El tejido es de Phifertex®, un microperforado, hilado de poliéster importado revestido de pvc, bajo las normas de calidad ISO 9001:2000-.',
        'ancho: 700 mm / alto: 370 mm / prof: 2000 mm',
        '',
        'https://i.ibb.co/qNZ8shT/1-8-1.jpg',
        'https://i.ibb.co/2j3rcFp/1-8-2.jpg',
        'https://i.ibb.co/QFB5bNH/1-8-3.jpg',
        'https://i.ibb.co/LCwL5kc/1-8-4.jpg',
        'https://i.ibb.co/y4GD2K7/1-8-5.jpg'
      ),
      new mueble(
        36,
        'Reposera Modena/ Phifertex®',
        'Colección Modena',
        'Reposeras',
        'Forma parte de la Colección Modena, diseñada con perfiles tubulares de aluminio a 45º y 90º, contiene el contorno de las patas sin corte. La cabecera es regulable según la necesidad de confort.Tejido microperforado, hilado de poliéster importado revestido de pvc, bajo las normas de calidad ISO 9001:2000-.',
        'ancho: 700 mm / alto: 250 mm / prof: 2000 mm',
        'https://i.ibb.co/mDRrzCZ/reposera-modena-croquis.jpg',
        'https://i.ibb.co/wKXy6LR/2-10-1.jpg',
        'https://i.ibb.co/b1xC0jh/2-10-2.jpg',
        'https://i.ibb.co/cDs81yB/2-10-3.jpg',
        'https://i.ibb.co/4M1BT91/2-10-4.jpg',
        'https://i.ibb.co/5vPnTBb/2-10-5.jpg'
      ),
      new mueble(
        37,
        'Reposera Modena/ Solarium®',
        'Colección Modena',
        'Reposeras',
        'Práctica y cómoda reposera, puede convertirse en sillón al poder regular su respaldo en 3 posiciones. Ideal para tomar sol en primavera y verano. El colchón está confeccionado en tela náutica lo cual permite permanecer expuesto al clima conservando todas sus prestaciones. Opcionales: 1 y 2 cuerpos.',
        '1 Cuerpo: An 0.700 mm. /Al 0.250 mm. /Prof 2.000 mm. || 2 Cuerpos: An 1.400 mm. /Al 0.250 mm. /Prof 2.000 mm.',
        'https://i.ibb.co/mDRrzCZ/reposera-modena-croquis.jpg',
        'https://i.ibb.co/WnJ9bhD/2-9-1.jpg',
        'https://i.ibb.co/WxySNVg/2-9-2.jpg',
        'https://i.ibb.co/L6sqdrm/2-9-3.jpg',
        'https://i.ibb.co/Qj2RJVg/2-9-4.jpg',
        'https://i.ibb.co/sPJgtyZ/2-9-5.jpg'
      ),
      new mueble(
        38,
        'Reposera Alumad',
        'Colección Alumad',
        'Reposeras',
        'Alumad presenta la combinación perfecta entre aluminio y madera en su versión ecológica y sintética. En todas las piezas de esta Coleccion, la estructura es de aluminio anodizado o pintado y la parte superior es de tablas de deck sintético, evitando todo tipo de deterioro al estar expuesto al sol y el agua. Disponemos de tres tonos de deck: blanco, marrón y gris.',
        'ancho: 700 mm / alto: 300 mm / prof: 1950 mm',
        '',
        'https://i.ibb.co/N95tK77/6-3-1.jpg',
        'https://i.ibb.co/wSWFh9w/6-3-2.jpg',
        'https://i.ibb.co/DkG792k/6-1-4.jpg',
        '',
        ''
      ),
      new mueble(
        39,
        'Reposera Belt',
        'Colección Belt',
        'Reposeras',
        'Empleando una nueva técnica, logramos líneas curvas y elegantes que dan como resultado un diseño único! Esta nueva línea está integrada por varios productos, es simple y divertida a la vez. Con sus diferentes piezas, esta colección nos propone jugar para armar diferentes diseños de livings. Con estructura de aluminio anodizado o pintado y tapicería en tela Sunbrella, Belt es para exterior!.',
        'ancho: 800 mm / alto: 520 mm / prof: 2000 mm',
        'https://i.ibb.co/gWnX7zw/reposera-belt-croquis.jpg',
        'https://i.ibb.co/0jWRfVW/7-4-1.jpg',
        'https://i.ibb.co/L9QRg57/7-4-2.jpg',
        'https://i.ibb.co/L9QRg57/7-4-2.jpg',
        '',
        ''
      ),
      /*camastro*/
      new mueble(
        40,
        'Camastro doble Solarium III',
        'Colección Modena',
        'Camastro',
        'descripcion',
        'Amplio Camastro de dos plazas. Coleccion Modena. Es ideal para situaciones de playa o solarium, permite recostarse y disfrutar de un coctail al aire libre. La medida en alto junto con el colchón es de 245 mm.',
        'ancho: 1400 mm / alto: 110 mm / prof: 2000 mm',
        '',
        'https://i.ibb.co/s1tVr41/2-13-1.jpg',
        'https://i.ibb.co/b79K6ZK/2-13-2.jpg',
        'https://i.ibb.co/b79K6ZK/2-13-2.jpg',
        ''
      ),
      new mueble(
        41,
        'Camastro Modena',
        'Colección Modena',
        'Camastro',
        'Lujosa protección frente al sol según el momento del día. Fabricado con perfilería de aluminio anodizado tubular y un sistema regulable de telas plásticas microperforadas en los laterales, cabecera y techo. La tapicería es desenfundable.',
        'ancho: 1500 mm / alto: 2000 mm / prof: 2000 mm',
        '',
        'https://i.ibb.co/9scFJ8K/2-14-1.jpg',
        'https://i.ibb.co/hFrbx2j/2-14-2.jpg',
        'https://i.ibb.co/GWRGXXQ/2-14-3.jpg',
        'https://i.ibb.co/brFbXW3/2-14-4.jpg',
        'https://i.ibb.co/KxLqSqZ/2-14-5.jpg'
      ),
      new mueble(
        42,
        'Camastro Cubo',
        'Colección Especial',
        'Camastro',
        'Camastro Cubo -doble-. Diseñado con un perfil de aluminio simple recto, con un ensamble perfecto entre sus atractivas terminaciones tanto rectas como curvilíneas. Los respaldos se pueden regular por separado, según la necesidad de confort. La cabecera y el techo están compuestos por una sucesión de varillas de alumino tubular. Esta materialidad le otorga una gran resistencia a todo tipo de clima. ',
        'ancho: 2000 mm / alto: 2000 mm / prof: 2000 mm',
        'https://i.ibb.co/VLWXy1R/camastro-cubo.jpg',
        'https://i.ibb.co/mCM8BGW/9-1-1.jpg',
        'https://i.ibb.co/3N6hXgN/9-1-2.jpg',
        'https://i.ibb.co/Gn4N9ks/9-1-3.jpg',
        'https://i.ibb.co/Wfks8TR/9-1-4.jpg',
        ''
      ),
      /*Barra*/
      new mueble(
        43,
        'Barra Formentera',
        'Colección Formentera',
        'Barra',
        'Forma parte de la Nueva Colección Formentera, diseñada con un perfil de aluminio simple (no tubular) con un ensamble perfecto entre sus atractivas terminaciones rectas. Tapa en melamina blanca. Opcionales tapa: varillas de aluminio, Deck, vidrio.',
        '105 x 54: An 1050 mm. / Al 1050 mm. / Prof 537 mm. ||  120 x 54: An 1200 mm. / Al 1050 mm. / Prof 537 mm. || 140 x 54: An 1400 mm. / Al 1050 mm. / Prof 537 mm. || 160 x 54: An 1600 mm. / Al 1050 mm. / Prof 537 mm. || 180 x 54: An 1800 mm. / Al 1050 mm. / Prof 537 mm.',
        '',
        'https://i.ibb.co/fHqmrWy/1-11-1.jpg',
        'https://i.ibb.co/z8rXpQd/1-11-2.jpg',
        'https://i.ibb.co/Mgtktpv/1-11-3.jpg',
        'https://i.ibb.co/jzGHmpw/1-11-4.jpg',
        ''
      ),
      new mueble(
        44,
        'Barra Modena',
        'Colección Modena',
        'Barra',
        'Barra Exterior fabricada en aluminio anodizado. Se destaca por tener un perfil extra como refuerzo en el piso. Opciones de Tapa: varillas de aluminio o tapa de laminado decorativo fenólico sólido fabricado a alta presión.',
        'An 1200 mm. /Al 1050 mm. /Prof 500 mm.  ||  An 1400 mm. /Al 1050 mm. /Prof 500 mm.  ||   An 1800 mm. /Al 1050 mm. /Prof 500 mm.',
        '',
        'https://i.ibb.co/bvZ7F4F/1-10-1.jpg',
        'https://i.ibb.co/3mxGmZR/1-10-2.jpg',
        'https://i.ibb.co/3mxGmZR/1-10-2.jpg',
        '',
        ''
      ),
      /*Banqueta*/
      new mueble(
        45,
        'Banqueta Formentera / Curva',
        'Colección Formentera',
        'Banquetas',
        'Banqueta Formentera / Curva / con Respaldo. Forma parte de la Nueva Colección Formentera, diseñada con un perfil de aluminio simple curvo, con un ensamble perfecto entre sus atractivas terminaciones tanto rectas como curvilíneas. Diseño opcional: Recto -perfiles con ángulos rectos-, c/s respaldo.',
        'ancho: 400 mm / alto: 730 mm / prof: 400 mm',
        '',
        'https://i.ibb.co/990Yy6G/1-15-1.jpg',
        'https://i.ibb.co/wQr5gg6/1-15-2.jpg',
        'https://i.ibb.co/Mgtktpv/1-11-3.jpg',
        '',
        ''
      ),
      new mueble(
        46,
        'Banqueta Formentera / Recta',
        'Colección Formentera',
        'Banquetas',
        'Diseñada con un perfil de aluminio simple recto, con un ensamble perfecto entre sus atractivas terminaciones tanto rectas como curvilíneas. Diseño opcional: Curvo -perfiles con ángulos rectos-.',
        'ancho: 370 mm / alto: 1070 mm / prof: 450 mm',
        '',
        'https://i.ibb.co/SyhJpYT/1-14-1.jpg',
        'https://i.ibb.co/8D1d3xY/1-14-2.jpg',
        'https://i.ibb.co/3MdYCfc/1-14-3.jpg',
        'https://i.ibb.co/4dRCnCk/1-14-4.jpg',
        ''
      ),
      new mueble(
        47,
        'Banqueta Modena',
        'Colección Modena',
        'Banquetas',
        'Fabricada en aluminio anodizado pulido. Ideal para combinar con la Barra Modena y/o Barra Formentera. Opcionales de tapa: Melamina / Tablillas de aluminio / Deck / Poliestileno de alta densidad.',
        'ancho: 450 mm / alto: 750 mm / prof: 450 mm',
        '',
        'https://i.ibb.co/GTn4m6W/2-16-1.jpg',
        'https://i.ibb.co/hHdf5Qq/2-16-2.jpg',
        'https://i.ibb.co/hHdf5Qq/2-16-2.jpg',
        '',
        ''
      ),
      new mueble(
        48,
        'Banqueta Modena / Con Respaldo',
        'Colección Modena',
        'Banquetas',
        'Forma parte de la Colección Modena, diseñada con perfiles tubulares de aluminio a 45º y 90º. Contiene el contorno de las patas sin corte. Tapa de melamina blanca. Mirá cómo hace juego con la Barra Tirreno y/o Barra Formentera.',
        'ancho: 350 mm / alto: 1050 mm / prof: 360 mm',
        'https://i.ibb.co/233ChKm/banqueta-modena-con-respaldo.jpg',
        'https://i.ibb.co/xgHHmSj/2-15-1.jpg',
        'https://i.ibb.co/JB1g49Q/2-15-2.jpg',
        'https://i.ibb.co/HBCWXH7/2-15-3.jpg',
        '',
        ''
      ),
      new mueble(
        49,
        'Banqueta Tirreno',
        'Colección Tirreno',
        'Banquetas',
        'Modelo único en su tipo. Se destaca por tener sólo 3 parantes en su diseño. Podés hacer juego con la Barra Tirreno. Fabricada en aluminio anodizado pulido. Opcionales de tapa: Melamina /Tablillas de aluminio / Deck /Poliestileno de alta densidad.',
        'ancho: 350 mm / alto: 740 mm / prof: 350 mm',
        '',
        'https://i.ibb.co/ccQqQ5x/3-5-1.jpg',
        'https://i.ibb.co/4gkXZ6y/3-5-2.jpg',
        'https://i.ibb.co/M278zf0/3-5-3.jpg',
        '',
        ''
      ),
      /*bancos*/
      new mueble(
        50,
        'Banco Formentera / Curvo',
        'Colección Formentera',
        'Bancos',
        'Banco Formentera / Curvo / sin Respaldo. Forma parte de la Nueva Colección Formentera, diseñada con un perfil de aluminio simple con un ensamble perfecto entre sus atractivas terminaciones tanto curvas como rectas. Diseño opcional: Recto -perfiles con ángulos rectos-.',
        '90: An 900 mm. /Al 380 mm. /Prof 450 mm. || 120: An 1200 mm. /Al 380 mm. /Prof 450 mm. || 150: An 1500 mm. /Al 380 mm. /Prof 450 mm. || 180: An 1800 mm. /Al 380 mm. /Prof 450 mm.',
        'https://i.ibb.co/SxdFth5/banco-formentera.jpg',
        'https://i.ibb.co/rwkZVxB/1-12-1.jpg',
        'https://i.ibb.co/qJLLzRg/1-12-2.jpg',
        'https://i.ibb.co/PjfGs2J/1-12-3.jpg',
        '',
        ''
      ),
      new mueble(
        51,
        'Banco Formentera / Recto',
        'Colección Formentera',
        'Bancos',
        'Banco Formentera / Recto / con Respaldo. Forma parte de la Nueva Colección Formentera, diseñada con un perfil de aluminio simple con un ensamble perfecto entre sus atractivas formas tanto rectas como curvilíneas. Diseño opcional: Curvo -perfiles con ángulos curvos-.',
        '90: An: 900 mm. / Al: 740 mm. / Prof: 550 mm. || 120: An: 1200 mm. / Al: 740 mm. / Prof: 550 mm. || 150: An: 1500 mm. / Al: 740 mm. / Prof: 550 mm. || 180: An: 1800 mm. / Al: 740 mm. / Prof: 550 mm.',
        'https://i.ibb.co/5R5Y84S/banco-formentera-con-respaldo.jpg',
        'https://i.ibb.co/3vtzHVq/1-13-1.jpg',
        'https://i.ibb.co/FXJNTrJ/1-13-2.jpg',
        'https://i.ibb.co/t2KxthJ/1-13-3.jpg',
        'https://i.ibb.co/r5rLChx/1-13-4.jpg',
        ''
      ),
      new mueble(
        52,
        'Banquito Deck',
        'Colección Deck',
        'Bancos',
        'Fabricado en aluminio anodizado -color marrón- combinado con tapa en Deck, es muy resistente a la intemperie. Opciones de tapa: melamina / tablillas de aluminio / polietileno de alta densidad.',
        'ancho: 350 mm || alto: 350 mm || prof: 350 mm',
        '',
        'https://i.ibb.co/tcd9Yds/8-4-1.jpg',
        'https://i.ibb.co/tcd9Yds/8-4-1.jpg',
        'https://i.ibb.co/tcd9Yds/8-4-1.jpg',
        '',
        ''
      ),
      new mueble(
        53,
        'Banco Alumad',
        'Colección Alumad',
        'Bancos',
        'Banco de la Colección Alumad, de líneas simples y robustas. Forma parte del comedor Alumad. Realizado en aluminio anodizado con tablas de deck sintético. Disponemos de tres tonos de deck: blanco, marrón y gris.',
        '1c // 1200 x 380 mm. x 450 mm. |      | 2c // 1500 x 380 mm. x 450 mm. |      |3c // 1800 x 380 mm. x 450 mm.',
        '',
        'https://i.ibb.co/cxg2p4T/6-5-1.jpg',
        'https://i.ibb.co/rfKrbN2/6-5-2.jpg',
        'https://i.ibb.co/cxz3GZ7/6-5-3.jpg',
        'https://i.ibb.co/RN9kCkM/6-5-4.jpg',
        ''
      ),
      new mueble(
        54,
        'Banco Alumad con Respaldo',
        'Colección Alumad',
        'Bancos',
        'Banco de la Colección Alumad, de líneas simples y robustas. Forma parte del comedor Alumad. Realizado en aluminio anodizado con tablas de deck sintético. Disponemos de tres tonos de deck: blanco, marrón y gris.',
        '1200 mm. x 380 mm. x 550 mm.    |    |   1500 mm. x 380 mm. x 550 mm.     |     |    1800 mm. x 380 mm. x 550 mm.',
        '',
        'https://i.ibb.co/5RGqrct/6-6-1.jpg',
        'https://i.ibb.co/z8hzNJn/6-6-3.jpg',
        'https://i.ibb.co/RN9kCkM/6-5-4.jpg',
        '',
        ''
      ),
      /*Silla*/
      new mueble(
        55,
        'Silla Alumad',
        'Colección Alumad',
        'Sillas',
        'Alumad presenta la combinación perfecta entre aluminio y madera en su versión ecológica y sintética. En todas las piezas de esta Coleccion, la estructura es de aluminio anodizado o pintado y la parte superior es de tablas de deck sintético, evitando todo tipo de deterioro al estar expuesto al sol y el agua. Disponemos de tres tonos de deck: blanco, marrón y gris.',
        'ancho: 450 mm / alto: 915 mm / prof: 455 mm',
        'https://i.ibb.co/kHPS5n8/silla-alumad.jpg',
        'https://i.ibb.co/DQgkc4D/6-4-1.jpg',
        'https://i.ibb.co/zXTGCZP/6-4-2.jpg',
        'https://i.ibb.co/ckmjYP5/6-4-3.jpg',
        'https://i.ibb.co/vcy1S6F/6-4-4.jpg',
        ''
      ),
      new mueble(
        56,
        'Silla Deck',
        'Colección Deck',
        'Sillas',
        'Fabricada en aluminio anodizado -color marrón- combinada con tapa en Deck de PVC, es muy resistente a la intemperie. Opciones de tapa: melamina / polietileno de alta densidad.',
        'ancho: 450 mm / alto: 915 mm / prof: 455 mm',
        'https://i.ibb.co/kHPS5n8/silla-alumad.jpg',
        'https://i.ibb.co/m0JHd7M/8-1-1.jpg',
        'https://i.ibb.co/bPCPpLr/8-1-2.jpg',
        'https://i.ibb.co/bPCPpLr/8-1-2.jpg',
        '',
        ''
      ),
      /*Hamacas*/
      new mueble(
        57,
        'Columpio',
        'Colección Especial',
        'Hamacas',
        'Fabricado con perfilería de aluminio anodizado y lonas de tela plástica Coversol. Capacidad máxima 4 personas. Carga máxima 300 kg.',
        'ancho: 2750 mm / alto: 2100 mm / prof: 220 mm',
        'https://i.ibb.co/QYrxN1q/hamaca-relax.jpg',
        'https://i.ibb.co/rvQ0736/9-7-1.jpg',
        'https://i.ibb.co/RYfh9Cx/9-7-2.jpg',
        'https://i.ibb.co/RYfh9Cx/9-7-2.jpg',
        '',
        ''
      ),
      new mueble(
        58,
        'Hamaca Picnic',
        'Colección Especial',
        'Hamacas',
        'Hamaca Picnic. Forma parte de la Colección Modena, diseñada con perfiles tubulares de aluminio a 45º y 90º, contiene el contorno de las patas sin corte. Ideal para sumar a espacios de entrenimiento y relax. Consultar por más colores.',
        'ancho: 900 mm / alto: 750 mm / prof: 500 mm',
        '',
        'https://i.ibb.co/b3bnq4V/9-6-1.jpg',
        'https://i.ibb.co/XSPjYN6/9-6-2.jpg',
        'https://i.ibb.co/XSPjYN6/9-6-2.jpg',
        '',
        ''
      ),
      new mueble(
        59,
        'Hamaca Cubo',
        'Colección Especial',
        'Hamacas',
        'Hamaca Cubo -doble- . Forma parte de la Colección Especial, diseñada con perfiles tubulares de aluminio a 45º y 90º, contiene el contorno de las patas sin corte. Ideal para sumar a espacios de entrenimiento y relax.',
        'ancho: 1360 mm / alto: 300 mm / prof: 1360 mm',
        '',
        'https://i.ibb.co/jgF827N/9-5-1.jpg',
        'https://i.ibb.co/jgF827N/9-5-1.jpg',
        'https://i.ibb.co/jgF827N/9-5-1.jpg',
        '',
        ''
      ),
      /*Pergola */
      new mueble(
        60,
        'Pérgola Bio',
        'Colección Especial',
        'Pérgolas',
        'La pérgola BIO ofrece una amplia variedad de posibilidades de construcción modular, mediante su diseño estructural flexible y compacto, que te permitirá ampliar la superficie habitable de tu hogar o negocio. Los modelos son autoportantes o se adosan directo a la pared. La escalabilidad la lográs uniendo módulos entre sí ya que pueden compartirse las columnas intermedias.Lamas orientables El techo de la pérgola está compuesto por un sistema de lamas móviles totalmente automatizadas. ',
        'Tamaño Personalizable',
        '',
        'https://i.ibb.co/Gc5j8f1/9-8-1.jpg',
        'https://i.ibb.co/BzG5F1h/9-8-2.jpg',
        'https://i.ibb.co/5xfXqcN/9-8-3.jpg',
        'https://i.ibb.co/CWrB4VX/9-8-4.jpg',
        ''
      ),
      new mueble(
        61,
        'Pérgola',
        'Colección Especial',
        'Pérgolas',
        '**Producto modular.** Fabricada totalmente a medida, las tablillas se colocan de frente y/o de perfil según el nivel de oscurecimiento que se busque. ',
        'Tamaño Personalizable',
        '',
        'https://i.ibb.co/HrLRKhh/9-9-1.jpg',
        'https://i.ibb.co/TrSzpB1/9-9-2.jpg',
        'https://i.ibb.co/TrSzpB1/9-9-2.jpg',
        '',
        ''
      ),
    ];
  }
  getMueble(id: any): mueble | any {
    return this.muebles.find((mueble) => mueble.idmuebles === parseInt(id));
  }
}
